### ISSUE TITLE
Node Red crashes with Oauth2

### ISSUE THREAD

**Issue by bouyssic** [caputomarcos/node-red-contrib-oauth2#5]
Hello team,

Hope you can help me. I'm having an issue using this. I seem to be experiencing crashes when the Authentication fails on my API (in this case I seem to have a http 500 for maintenance)

Here is what I have on my debug logs
```
15 Mar 11:22:24 - SyntaxError: Unexpected token < in JSON at position 0
at JSON.parse (<anonymous>)
at Request._callback (/data/node_modules/node-red-contrib-oauth2/oauth2.js:120:31)
at Request.self.callback (/data/node_modules/request/request.js:185:22)
at Request.emit (events.js:198:13)
at Request.<anonymous> (/data/node_modules/request/request.js:1161:10)
at Request.emit (events.js:198:13)
at IncomingMessage.<anonymous> (/data/node_modules/request/request.js:1083:12)
at Object.onceWrapper (events.js:286:20)
at IncomingMessage.emit (events.js:203:15)
at endReadableNT (_stream_readable.js:1145:12)
at process._tickCallback (internal/process/next_tick.js:63:19)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-red-docker@1.0.4 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
npm ERR! Exit status 1


npm ERR! Failed at the node-red-docker@1.0.4 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /usr/src/node-red/.npm/_logs/2020-03-15T10_22_24_188Z-debug.log

> node-red-docker@1.0.4 start /usr/src/node-red
> node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"
```

Since this is running in Docker, I lose "/usr/src/node-red/.npm/_logs/2020-03-15T10_22_24_188Z-debug.log" when the container drops.

Nevertheless if I manually force an error, like give wrong credentials, I don't seem to have the issue.

Can you help me debug this down?

Regards
Chris

**Comment by bouyssic** [comment]
I got the log from the error here it is : 
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'start',
1 verbose cli   '--',
1 verbose cli   '--userDir',
1 verbose cli   '/data' ]
2 info using npm@6.13.4
3 info using node@v10.19.0
4 verbose config Skipping project config: /usr/src/node-red/.npmrc. (matches userconfig)
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info lifecycle node-red-docker@1.0.4~prestart: node-red-docker@1.0.4
7 info lifecycle node-red-docker@1.0.4~start: node-red-docker@1.0.4
8 verbose lifecycle node-red-docker@1.0.4~start: unsafe-perm in lifecycle true
9 verbose lifecycle node-red-docker@1.0.4~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/usr/src/node-red/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
10 verbose lifecycle node-red-docker@1.0.4~start: CWD: /usr/src/node-red
11 silly lifecycle node-red-docker@1.0.4~start: Args: [ '-c',
11 silly lifecycle   'node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"' ]
12 silly lifecycle node-red-docker@1.0.4~start: Returned: code: 1  signal: null
13 info lifecycle node-red-docker@1.0.4~start: Failed to exec start script
14 verbose stack Error: node-red-docker@1.0.4 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
14 verbose stack     at EventEmitter.emit (events.js:198:13)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
14 verbose stack     at ChildProcess.emit (events.js:198:13)
14 verbose stack     at maybeClose (internal/child_process.js:982:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
15 verbose pkgid node-red-docker@1.0.4
16 verbose cwd /usr/src/node-red
17 verbose Linux 4.19.98-Unraid
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start" "--" "--userDir" "/data"
19 verbose node v10.19.0
20 verbose npm  v6.13.4
21 error code ELIFECYCLE
22 error errno 1
23 error node-red-docker@1.0.4 start: `node $NODE_OPTIONS node_modules/node-red/red.js $FLOWS "--userDir" "/data"`
23 error Exit status 1
24 error Failed at the node-red-docker@1.0.4 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

Does not help me much understand what happens

**Comment by bouyssic** [comment]
I was able to crudely patch the issue, again am not developer whatsoever. 
I've created a PR if anybody wants to see what I did 
https://github.com/caputomarcos/node-red-contrib-oauth2/pull/6

**Comment by caputomarcos** [comment]
Hi @bouyssic, all done!  I made the changes requested, could you review it please?

best regard

**Comment by bouyssic** [comment]
hi @caputomarcos ,

I don't use this anymore on my end. I can't validate this for you unfortunately. 

Regards
